### ISSUE TITLE
YAML vs JSON

### ISSUE THREAD

**Issue by myroslav** [gosquadron/squadron#17]
Have you considered YAML instead (or in addition to) JSON for suqadron configuration files? Sysadmins like to have configurations as simple as possible, thus Makefile, ini-configs, yaml, etc. The [Configuration from docs](http://docs.gosquadron.com/en/latest/gettingstarted.html#configuration) would look like:

``` yaml
base_dir: /var/www
config:
  disallow:
    - /secret/*
    - /admin/*
  release: master
version: 0.0.1
```

 The [Schema from docs](http://docs.gosquadron.com/en/latest/gettingstarted.html#schema) would look like:

``` yaml
$schema: http://json-schema.org/draft-04/schema#
type: object
properties: 
    disallow:
        description: a list of disallow directives
        type: array
        items:
            type: string
        uniqueItems: true
    release:
        description: what to checkout from the git repository
        type: string
required:
  - disallow
  - release
```
